### ISSUE TITLE
Usage on Plan9 instructions?

### ISSUE THREAD

**Issue by driusan** [sirnewton01/acme-twitter#2]
When I try running acme-twitter under 9front I get the error:

```
panic: open /usr/driusan/.trc: '/usr/driusan/.trc' does not exist

goroutine 1 [running]:
main.main()
	/usr/driusan/gopath/src/github.com/sirnewton01/acme-twitter/main.go:32 +0x71c
term% acme-twitter authorize
panic: open /usr/driusan/.trc: '/usr/driusan/.trc' does not exist

goroutine 1 [running]:
main.main()
	/usr/driusan/gopath/src/github.com/sirnewton01/acme-twitter/main.go:32 +0x71c
```

Presumably this is just because the .trc file doesn't exist. The instructions point to the `t` tool, but the `t` tool is written in Ruby and the instructions on their README just invoke their own subcommands. Are there instructions somewhere on how to get this working on Plan 9?

**Comment by sirnewton01** [comment]
No, sorry, I'm not aware how to get this working in Plan 9 other than to generate the file on Linux and then copy it over. Agreed that the error message is super non-friendly.
